### ISSUE TITLE
[$100] Your bug title goes here!2

### ISSUE THREAD

**Issue by RCheesley** [RCheesley/mautic#26]
### Mautic Version

5.0.x series

### PHP version

8

### What happened?

A bug happened!

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct
<br />
<hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team!

**Comment by bilalshaikh292** [comment]
heyy is the issue still open and does it have a bounty associated with it ?

**Comment by RCheesley** [comment]
No, it was a test issue. Thanks!
